### ISSUE TITLE
Error adding spider-client

### ISSUE THREAD

**Issue by ShravanSunder** [spider-rs/spider-clients#7]
With the new version (25) i'm getting the following error

Failed to download and build `spider-client==0.0.25`
  Caused by: Failed to build: `spider-client==0.0.25`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/shravansunder/Library/Caches/uv/.tmpTsPtnm/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shravansunder/Library/Caches/uv/.tmpTsPtnm/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/Users/shravansunder/Library/Caches/uv/.tmpTsPtnm/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/shravansunder/Library/Caches/uv/.tmpTsPtnm/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shravansunder/Library/Caches/uv/built-wheels-v3/index/b2a7eb67d4c26b82/spider-client/0.0.25/wimFyp9dxBcU34AmgbwFT/spider-client-0.0.25.tar.gz/version.py'

**Comment by j-mendez** [comment]
fixed in `v0.0.26` ty
